source/index.html.md

add sender bank in parameter callback

add Param in callback parameter

---

source/index.html.md

Release V2 Payment Checkout 
add warning V1 to be deprecated

[Doc Update Release V2] deprecated v1 and Release V2

---

source/index.html.md

Sample curl

---

source/index.html.md

Updating content and feedback from BD

---

source/index.html.md

Update column information

---

source/index.html.md

Reverts oyindonesia/oybayar-docs#15

Revert "Update index.html.md"

---

source/index.html.md

Add info about transaction queue and minimum e wallet amount

---

source/index.html.md

Update wording minimum amount

---

source/index.html.md

update minimum wording

---

source/index.html.md

Update bulk upload limit

---

source/index.html.md

update statusfinish and incomplete for bulk disbursement

update status bulk disbursement

---

source/stylesheets/screen.css.scss

Hotfix about add scrollbar in codeblock (unhide scrollbar in codeblock)
You can check in https://fir-app-cd1ac.web.app

[HOTFIX] Add scrollbar in Codeblock

---

source/layouts/layout.erb

Change link to dashboard in header
You can check in https://fir-app-cd1ac.web.app/

[HOTFIX] change link dashboard in header 

---

source/javascripts/all_nosearch.js
source/javascripts/app/_toc.js

- Fixing dropdown list h3 (auto close dropdown, just open specific list h3 that corresponding with page)
Before
After
You can check in https://fir-app-cd1ac.web.app/

Fixing dropdown TOC list h3

---

source/includes/_accepting-payments.md

Separating invoice

---

source/includes/_accepting-payments.md

Separate Invoice & Payment Checkout

---

source/includes/_accepting-payments.md

Fix Monitoring PC section

---

source/includes/_oy-tutorial.md

Fix registration & setup heading

---

source/images/logo.svg
source/includes/_accepting-payments.md
source/includes/_faq.md
source/includes/_home.md
source/includes/_oy-tutorial.md

Change Payment Checkout wording to Payment Link

---

source/includes/_accepting-payments.md

PayRout update -add description payment routing

---

source/includes/_accepting-payments.md

PayRout update - delete API VA and API Payment Link to prevent misleading

---

source/includes/_accepting-payments.md

update payrout keyfeature

---

source/includes/_accepting-payments.md

Add in testing section

---

source/includes/_accepting-payments.md

edit ewallet product docs

---

source/includes/_sending-payments.md

Title, will revert if deemed need to be

Change some example to test auto deployment

---

source/includes/_accepting-payments.md

Update BNI - Open Amount

---

source/includes/_sending-payments.md

delete overbooking wording from product docs

---

source/includes/_oy-tutorial.md

change top up image of no va bni

---

source/includes/_oy-tutorial.md

change wording for Analytics

---

source/includes/_oy-tutorial.md

Add xero product docs

---

source/includes/_business-app.md

add business app section in business app

---

source/index.html.md

add business app section in product docs-add index

---

source/includes/_accepting-payments.md

Add VA BSI in Docs

---

source/includes/_accepting-payments.md

Add details of Maybank Danamon Hana to public product docs

Add VA Maybank Danamon Hana to Product Docs 

---

source/includes/_sending-payments.md

virtualcard_18oct

---

source/includes/_oy-tutorial.md

Add Accurate accounting platform product docs

---

source/includes/_oy-tutorial.md

add top up bca unique code product docs

---

source/includes/_accepting-payments.md

update: VA example update revision 

---

source/includes/_accepting-payments.md

add VA Number customization in product docs

add VA customized feature in the docs

---

.github/workflows/build.yml

Remove Gem Update Command

---

source/includes/_home.md
source/includes/_oy-tutorial.md

update images and some wordings regis login top up

---

source/includes/_accepting-payments.md

updating to add details in product docs for mock cc/dc callback feature

update docs to add details for mock cc callback feature

---

source/includes/_accepting-payments.md

Account Linking & DANA Tokenization

---

source/includes/_accepting-payments.md

Enable E-Wallet API Based in Payment Routing

---

source/includes/_sending-payments.md

- Fix wrong image rendering
- Fix wrong bullet points format

International Remittance fixes

---

source/includes/_sending-payments.md

Fix bullet points

---

source/includes/_accepting-payments.md

add cc/dc details disclaimer to ensure clients understand that their end users need to enable 3DS, have sufficient balance, and use our supported principals to conduct the trx successfully

add cc/dc details for pmt link & routing

---

source/includes/_accepting-payments.md

the spacing for the cc/dc details was off & need to also add disclaimer for overseas trx

edit cc/dc details & add overseas trx too

---

source/includes/_accepting-payments.md

create new section for cc/dc trx to include more info & adjust the formatting for account linking

add details for cc/dc trx & adjust formatting for account linking

---

source/includes/en/_accepting-payments.md

Hotfix Dummy Staging Callbac

---

source/includes/en/_accepting-payments.md
source/includes/en/_sending-payments.md
source/includes/id/_accepting-payments.md
source/includes/id/_sending-payments.md

BusinessBankingNov23

---

.github/workflows/deploy.yml

Adjust ubuntu version for deploy

---

source/includes/en/_sending-payments.md

Add international transfer approval flow details

international transfer approval flow changes

---

source/includes/en/_accepting-payments.md

take out nicepay - hana, maybank, danamon as our partnership w nicepay is terminated

disable nicepay banks (hana, danamon, maybank)

---

source/includes/en/_sending-payments.md

Update available countries: CN & HK and currencies: CNY and HKD and slight wording in roles

Edit available countries, currencies and wording in roles

---

source/includes/en/_sending-payments.md

Edit layout, spacing newlines and wordings

Edit layout, spacing newlines and wordings

---

source/includes/en/_accepting-payments.md

update min amt for payment link VA CIMB Mandiri Permata transactions (due to IFP integration)

update minimum amount for PL CIMB Mandiri Permata

---

Dockerfile
docker-compose.yml

Fixes all issue when serving docs locally via docker-compose
- Ruby gem pinning
- Undefined constant Rouge::Theme::Oy

Fix local serve using docker-compose

---

source/includes/en/_accepting-payments.md

Reduce VA BTPN max amount from Rp500.000.000 to Rp100.000.000 as [per discussion](https://oyteam.slack.com/archives/C01MBSYV23T/p1719830008029349?thread_ts=1719375395.556169&cid=C01MBSYV23T)

Update: Adjust VA BTPN max amount to 100jt

---

source/includes/en/_accepting-payments.md
source/includes/id/_accepting-payments.md
source/includes/id/_faq.md

chore: Adjust VA docs

---

source/includes/id/_expense-management.md

Expensemgmt

---

source/includes/en/_sending-payments.md

update xm to sending payments

---

source/localizable/index.en.html.md
source/localizable/index.id.html.md

add section

---

source/includes/en/_sending-payments.md

fix numbering AP

---

docker-compose.yml
source/includes/en/_accepting-payments.md

Clear up BNI Open Amount capabilities

chore: clear up bni open amount capability

---

source/includes/en/_sending-payments.md

fixing numbering AP

---

source/includes/en/_sending-payments.md

fixing numbering AP using span

---

source/includes/en/_accepting-payments.md

Improve: Change Name BTPN to SMBC

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/dev_deploy.yml
.github/workflows/publish.yml
source/includes/en/_accepting-payments.md

[Acceptance] Adjust Max Amount per Transaction Info for SMBC

---

source/includes/id/_accepting-payments.md

Fix Wording "Alur Transaksi Pembayaran" to "Alur Pembayaran" tab Unique Code

[Acceptance] Fix Wording "Alur Transaksi Pembayaran" to "Alur Pembayaran" tab Unique Code
